export const COMPANIES = [
    {
      id: 1,
      CompanyName:"RENAUD " ,
      Forme_Juridique:"Entrepreneur individuel" ,
      Depuis_le :"01/10/2015" ,
      ACtivité: "Traduction et interprétation",
      Code_NAF:"74.30Z" , 
      Lieu:"SAINT-ROMAIN-DE-BENET",
      Code_postal:"17600",
      Effectif:"0 salarié",
    },
    {
        id: 2,
        CompanyName:"CHAUMES FABIEN" ,
        Forme_Juridique:"Entrepreneur individuel",
        Depuis_le :" 13/01/2013",
        ACtivité:"Activités des infirmiers et des sages-femmes",
        Code_NAF:"86.90D",
        Lieu:"NERAC",
        Code_postal:"47600 + 1 autre ville ",
        Effectif:"0 salarié",
      },
      {
        id: 3,
        CompanyName:"VIVIER DIDIER " ,
        Forme_Juridique:"Entrepreneur individuel",
        Depuis_le :" 13/01/2013",
        ACtivité:"Activités des infirmiers et des sages-femmes",
        Code_NAF:"86.90D",
        Lieu:"NERAC",
        Code_postal:"47600 + 1 autre ville ",
        Effectif:"0 salarié",
      },
      {
        id: 4,
        CompanyName:"JARLES CLAUDE " ,
        Forme_Juridique:"Entrepreneur individuel",
        Depuis_le :" 13/01/2013",
        Activité:"Activités des infirmiers et des sages-femmes",
        Code_NAF:"86.90D",
        Lieu:"NERAC",
        Code_postal:"47600 + 1 autre ville ",
        Effectif:"0 salarié",
      },
      {
        id: 5,
        CompanyName:"LEBRUN FABIENNE " ,
        Forme_Juridique:"Entrepreneur individuel",
        Depuis_le :" 13/01/2013",
        ACtivité:"Activités",
        Code_NAF:"86.90D",
        Lieu:"NERAC",
        Code_postal:"47600 + 1 autre ville ",
        Effectif:"0 salarié",
      },
      {
        id: 6,
        CompanyName:"SOCQUET THIERRY " ,
        Forme_Juridique:"Entrepreneur individuel",
        Depuis_le :" 13/01/2013",
        ACtivité:"Activités sages-femmes",
        Code_NAF:"86.90D",
        Lieu:"NERAC",
        Code_postal:"47600 + 1 autre ville ",
        Effectif:"0 salarié",
      },
    
]